---
# The main magento playbook
# Mischa van den Burg & Gino Kok

- name: Vuls setup
  hosts: all

  roles:

    - role: docker_installer
      tags:
        - docker-install
        - global-install

    - role: vuls_install
      tags:
        - vuls-install
        - global-instal