---

- name: Vuls setup
  hosts: all

  roles:
    # Role for installing docker
    - role: docker_installer
      tags:
        - docker-install

    # Role for installing vuls
    - role: vuls_install
      tags:
        - vuls-install

    # Role for running vuls
    - role: run_vuls
      tags:
        - run-vuls

    # Role for running vuls repo container
    - role: run_vuls_repo
      tags:
        - run-vuls-repo
