---
# This role installs Docker for centos 8 and enables it on boot

  # Make sure we have the latest yum utils version
  - name: Install required packages
    package:
      name: 
        - python3
        - python3-pip
      state: latest
    become: true

# You can use shell to run other executables to perform actions inline
  - name: Install docker
    shell: |
      curl -fsSL https://get.docker.com -o /tmp/get-docker.sh \
      sudo sh /tmp/get-docker.sh \
      rm -r /tmp/get-docker.sh

  # Retrieves the docker version
  - name: get docker version
    shell: "docker -v"
    register: version

  # Prints out the installed docker version
  - debug: var=version.stdout
  
  # Starts the docker service and enables docker on boot
  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes

  # Install the Docker SDK module      
  - name: Install Docker SDK
    pip:
      name: docker
...
