---
# This role installs Docker for centos 8 and enables it on boot

  # Make sure we have the latest yum utils version
  - name: Install required packages
    apt:
      name: 
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
    become: true

    # Add docker gpg key
  - name: Add docker gpg key
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg"

    # Set up stable docker repository
  - name: Set up stable docker repository
    shell: |
      echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Install docker
  - name: Install docker
    apt:
      name: 
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      update_cache: 
      state: latest
    become: true
  
  # Starts the docker service and enables docker on boot
  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes

  # Install the Docker SDK module      
  - name: Install Docker SDK
    pip:
      name: docker

  # Add user to the docker group
  - name: Add user to the docker group
    become: true
    user:
        name: "ubuntu"
        groups: docker
        append: yes

  # Reset ssh connection to be able to use the group
  - name: reset ssh connection to allow user changes to affect the user
    meta:
      reset_connection

  - name: show docker containers
    shell: "docker container ls"
    register: containers

  # Prints out the installed docker version
  - debug: var=containers.stdout
...
