---
# Make sure we have the latest required packages
- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: true

# Add docker gpg key
- name: Add docker gpg key
  ansible.builtin.shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
   | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg"

# Set up the stable docker repository
- name: Set up stable docker repository
  ansible.builtin.shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install docker + dependencies
- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache:
    state: present
  become: true

# Starts the docker service and enables docker on boot
- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

# Install the Docker SDK module
- name: Install Docker SDK
  ansible.builtin.pip:
    name: docker

# Add user to the docker group
- name: Add user to the docker group
  become: true
  ansible.builtin.user:
    name: "ubuntu"
    groups: docker
    append: yes

# Reset ssh connection to be able to use the group
- name: reset ssh connection to allow user changes to affect the user
  ansible.builtin.meta:
    reset_connection
...
