---

  # Make sure we have git installed
  - name: Install git
    apt:
      name: 
        - git
      state: latest
    become: true

  # Clone the vuls repo
  - name: clone vuls repository
    git:
      repo: "https://github.com/vulsio/vulsctl.git"
      dest: $HOME/vulsctl
      force: yes

  - name: update scripts
    shell: sed -i 's/\$PWD/\~\/vulsctl\/docker/' ~/vulsctl/docker/{{ item }}
    with_items: [ 'scan.sh', 'report.sh', 'oval.sh' ]

...
