---

  # Make sure we have git installed
  - name: Install git
    apt:
      name: 
        - git
      state: latest
    become: true

  # Clone the vuls repo
  - name: clone vuls repository
    git:
      repo: "https://github.com/vulsio/vulsctl.git"
      dest: $HOME/vulsctl

  - name: update scan.sh
    shell: sed -i 's/\$PWD/\~\/vulsctl\/docker/' ~/vulsctl/docker/scan.sh

  - name: update report.sh
    shell: sed -i 's/\$PWD/\~\/vulsctl\/docker/' ~/vulsctl/docker/report.sh
...
